DTSPO-12032: Revert logic for apply in cnp library
hmcts/cnp-azuredevops-libraries pull request #130
Opened 2023-01-09 15:30 UTC by madjava

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSPO-12032

### Change description ###
Reverting back to original logic as this would now allow every other repo using the library to be able to apply from branch which is what we don't want.

May i suggest and additional condition/variable be added e.g.
`and(succeeded(), eq('${{ parameters.overrideAction }}', 'apply'), eq('${{ parameters.applyOnBranch }}', 'true'))`

So that if a project/repo has need to specifically apply on branch, then that project can pass the additional parameter to facilitate this.

Default value for `applyOnBranch` would be false so other repos are still happy

All others remain as before where `apply` only happens either on `main` or on merge of the `main` branch.

Happy for further conversations or suggestion, and happy for that to be implemented as well 😜
@louisehuyton , @msl8r , @timja 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-01-10 16:46 UTC, timja requested changes
> Reverting back to original logic as this would now allow every other repo using the library to be able to apply from branch which is what we don't want.

Why don't you want to do this?

It allows us to do staged rollouts and to test before merging, this change was applied because it prevented us from properly testing CD repositories

2023-01-11 09:50 UTC, madjava commented
> > Reverting back to original logic as this would now allow every other repo using the library to be able to apply from branch which is what we don't want.
> 
> Why don't you want to do this?
> 
> It allows us to do staged rollouts and to test before merging, this change was applied because it prevented us from properly testing CD repositories

So i am suggesting that we do it in a different way not remove the functionality, i understand that it's needed. Doing it this way will mean that every other repo can apply from a PR not just your use case.

2023-01-11 09:54 UTC, timja commented
> So i am suggesting that we do it in a different way not remove the functionality, i understand that it's needed. Doing it this way will mean that every other repo can apply from a PR not just your use case.

Would you be able to explain your reasoning a bit more? "Which way"? 

> So i am suggesting that we do it in a different way not remove the functionality, i understand that it's needed. Doing it this way will mean that every other repo can apply from a PR not just your use case.

the current pull request seems to be a straight revert which does not enable the required functionality.

2023-01-18 14:30 UTC, msl8r commented
Bit late to the party here, but you could just add an if statement to your pipeline that sets the `overrideAction` to plan if the branch isn't main?

Made an example PR below, might not be perfect but it gives you an idea @madjava 

https://github.com/hmcts/hub-panorama-terraform/pull/331/files

2023-06-19 15:21 UTC, closed without merging

2023-06-19 15:21 UTC, madjava commented
dud